petstore:
  service:
    pet:
      url: ${PETSTOREPETSERVICE_URL:http://localhost:8081}
    product:
      url: ${PETSTOREPRODUCTSERVICE_URL:http://localhost:8082}
    order:
      url: ${PETSTOREORDERSERVICE_URL:http://localhost:8083}
  security:
    # Enable in Module 10
    enabled: ${PETSTORE_SECURITY_ENABLED:false}
server:
  port: ${PETSTOREAPP_SERVER_PORT:8080}
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    ssl:
      enabled: false
    diskspace:
      enabled: false
    applicationinsights:
      enabled: false
    security:
      enabled: false
spring:
  application:
    name: petstoreapp
  thymeleaf:
    cache: false
  cache:
    cache-names: currentUsers
  cloud:
    discovery:
      enabled: false
    refresh:
      enabled: false
  security:
    # Used in Module 10
    oauth2:
      client:
        registration:
          azure:
            client-id: ${AZURE_CLIENT_ID}
            client-secret: ${AZURE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
        provider:
          azure:
            authorization-uri: https://${AZURE_TENANT_DOMAIN}.ciamlogin.com/${AZURE_TENANT_DOMAIN}.onmicrosoft.com/oauth2/v2.0/authorize
            token-uri: https://${AZURE_TENANT_DOMAIN}.ciamlogin.com/${AZURE_TENANT_DOMAIN}.onmicrosoft.com/oauth2/v2.0/token
            jwk-set-uri: https://${AZURE_TENANT_DOMAIN}.ciamlogin.com/${AZURE_TENANT_DOMAIN}.onmicrosoft.com/discovery/v2.0/keys
            user-name-attribute: sub
logging:
  level:
    root: INFO
    com.chtrembl.petstoreapp: INFO
    com.azure.monitor.opentelemetry.autoconfigure.implementation.quickpulse.QuickPulsePingSender: ERROR
    com.azure.core.http.netty.NettyAsyncHttpClient: ERROR